# Daily fetch from website

name: daily-fetch

on:
    schedule:
     # Runs at UTC 1 am every day
     # Run at every 10 minutes for test
     - cron: '0 0 * * *'

    workflow_dispatch:

jobs:
  fetch:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Clean up
      run: |
        ls -A
        rm -r $(ls -A | grep -vE ".github|.git|README.adoc")
        echo 'cleaned up the old data'
        ls -A

    - name: Fetch BIPM data
      run: |
        gem install bipm-data-importer
        gem install webmock
        bipm-fetch --fork
        bipm-fetch-cgpm

    - name: Move generated outcomes to outcomes
      run: |
        mv ./data/* ./
        ls -A

    - name: Push new data
      env:
        CI_COMMIT_MESSAGE: Daily Update
        CI_COMMIT_AUTHOR: Daily Update
        CI_COMMIT_EMAIL: metanorma@ribose.com
      run: |
        test -d cipm
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
        git add . || :
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}" || :
        git push || :
