# Daily fetch bipm website

name: Daily Scrapper

on: 
    schedule:
     # Runs at UTC 1 am every day
     # Run at every 10 mintues for test
     - cron: '0 0 * * *'  

    workflow_dispatch:

jobs:
  scrap:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Clean up
      run: |
        ls -A
        rm -r $(ls -A | grep -vE ".github|.git|README.adoc")
        echo 'cleaned up the old data'
        ls -A

    - name: Scrap bipm data
      run: |
        gem install bipm-data-importer
        gem install webmock
        bipm-fetch --fork
        bipm-fetch-cgpm
    
    - name: Move generated outcomes to outcomes
      run: |
        mv -rf ./data/* ./
        ls -A
    
    - name: Push new data
      env: 
        CI_COMMIT_MESSAGE: Daily Update
        CI_COMMIT_AUTHOR: Daily Update
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "bot@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}" || :
        git push || :
